
import type { Product } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Men Slim Fit Casual Shirt',
    brand: 'DENNISLINGO PREMIUM ATTIRE',
    price: 499,
    description: 'A stylish slim fit casual shirt for men, perfect for any occasion. Made with high-quality cotton.',
    imageUrl: 'https://picsum.photos/seed/product1/600/800',
    category: 'Men',
  },
  {
    id: '2',
    name: 'Women High-Rise Skinny Fit Jeans',
    brand: 'LEVI\'S',
    price: 1399,
    description: 'Classic high-rise skinny fit jeans that hug your curves in all the right places. Durable and comfortable.',
    imageUrl: 'https://picsum.photos/seed/product2/600/800',
    category: 'Women',
  },
  {
    id: '3',
    name: 'Unisex Running Shoes',
    brand: 'NIKE',
    price: 3495,
    description: 'Lightweight and responsive running shoes designed for speed and comfort over long distances.',
    imageUrl: 'https://picsum.photos/seed/product3/600/800',
    category: 'Footwear',
  },
  {
    id: '4',
    name: 'Floral Print A-line Dress',
    brand: 'FUSION',
    price: 899,
    description: 'A beautiful A-line dress with a vibrant floral print, perfect for summer outings.',
    imageUrl: 'https://picsum.photos/seed/product4/600/800',
    category: 'Women',
  },
  {
    id: '5',
    name: 'Men\'s Graphic Print T-shirt',
    brand: 'THE INDIAN GARAGE CO',
    price: 359,
    description: 'A comfortable cotton t-shirt with a cool graphic print. A great addition to your casual wardrobe.',
    imageUrl: 'https://picsum.photos/seed/product5/600/800',
    category: 'Men',
  },
  {
    id: '6',
    name: 'Analog Watch with Leather Strap',
    brand: 'FOSSIL',
    price: 5995,
    description: 'A timeless analog watch with a genuine leather strap that adds a touch of class to any outfit.',
    imageUrl: 'https://picsum.photos/seed/product6/600/800',
    category: 'Accessories',
  },
    {
    id: '7',
    name: 'Women\'s Solid Tote Bag',
    brand: 'LINO PERROS',
    price: 1499,
    description: 'A spacious and stylish tote bag to carry all your essentials. Features a clean, solid design.',
    imageUrl: 'https://picsum.photos/seed/product7/600/800',
    category: 'Accessories',
  },
  {
    id: '8',
    name: 'Men\'s Slim Fit Chinos',
    brand: 'U.S. POLO ASSN.',
    price: 1249,
    description: 'Versatile slim fit chinos that can be dressed up or down for any occasion.',
    imageUrl: 'https://picsum.photos/seed/product8/600/800',
    category: 'Men',
  },
];
